### ISSUE TITLE
What is -lprotobuf in Chapter02 CMakeFile.txt?

### ISSUE THREAD

**Issue by jean-rl** [PacktPublishing/Building-Computer-Vision-Projects-with-OpenCV4-and-CPlusPlus#1]
I get an error when running `make -j6` with -lprotobuf. I see you added it here, but in the book Chapter2 "Reading videos and cameras" the flag doesn't appear.

`TARGET_LINK_LIBRARIES( ${PROJECT_NAME} ${OpenCV_LIBS} ${CONAN_LIBS} -lprotobuf)`

Thanks in advance.

**Comment by thatrobotguy** [comment]
Well, I don't know why you need `protobuf`, but `protobuf` refers to Google's Protocol Buffers. It is a cross-platform, language-agnostic data serialization and de-serialization library. It allows you to send data through sockets between a C# program and a Python script because the message description format is the same for both and the `protoc` compiler creates the class files required to use these message formats. I suggest you search more about them as they are super useful for machine-to-machine communication.

I am not sure why it is there though: it may or may not be necessary.
